// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessedEvent = `-- name: CreateProcessedEvent :one
INSERT INTO enrollment.processed_events (event_id, event_type, processed_at)
VALUES ($1, $2, NOW())
RETURNING event_id, event_type, processed_at
`

type CreateProcessedEventParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, createProcessedEvent, arg.EventID, arg.EventType)
	var i ProcessedEvent
	err := row.Scan(&i.EventID, &i.EventType, &i.ProcessedAt)
	return i, err
}

const deleteOldProcessedEvents = `-- name: DeleteOldProcessedEvents :execrows
DELETE FROM enrollment.processed_events
WHERE processed_at < $1
`

// Retention: the dedup ledger only has to outlive redelivery, not the row it
// guarded. Retention window comes from the caller, not the query.
func (q *Queries) DeleteOldProcessedEvents(ctx context.Context, processedAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldProcessedEvents, processedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(
    SELECT 1 FROM enrollment.processed_events WHERE event_id = $1
) as processed
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}
