// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: periods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPeriod = `-- name: CreatePeriod :one

INSERT INTO course_catalog.academic_periods (semester, period_start, period_end, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, semester, period_start, period_end, is_active, created_at, updated_at
`

type CreatePeriodParams struct {
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
}

type CreatePeriodRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// academic_periods now holds one row per period_type, not one per semester.
// Only DeletePeriodsBySemester below is still called (it clears every type for
// a semester, which is what semester deletion wants). Every other query here
// is unused and NOT type-scoped — reading through one would return an
// arbitrary service's period. Use SimplePeriodRepository, which scopes by
// type, or add the period_type predicate before wiring one of these up.
func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (CreatePeriodRow, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.Semester,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IsActive,
	)
	var i CreatePeriodRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePeriod = `-- name: DeletePeriod :exec
DELETE FROM course_catalog.academic_periods WHERE id = $1
`

func (q *Queries) DeletePeriod(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePeriod, id)
	return err
}

const deletePeriodsBySemester = `-- name: DeletePeriodsBySemester :exec
DELETE FROM course_catalog.academic_periods WHERE semester = $1
`

func (q *Queries) DeletePeriodsBySemester(ctx context.Context, semester string) error {
	_, err := q.db.Exec(ctx, deletePeriodsBySemester, semester)
	return err
}

const getActivePeriodBySemester = `-- name: GetActivePeriodBySemester :one
SELECT id, semester, period_start, period_end, is_active, created_at, updated_at
FROM course_catalog.academic_periods
WHERE semester = $1 AND is_active = true
LIMIT 1
`

type GetActivePeriodBySemesterRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActivePeriodBySemester(ctx context.Context, semester string) (GetActivePeriodBySemesterRow, error) {
	row := q.db.QueryRow(ctx, getActivePeriodBySemester, semester)
	var i GetActivePeriodBySemesterRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriodByID = `-- name: GetPeriodByID :one
SELECT id, semester, period_start, period_end, is_active, created_at, updated_at
FROM course_catalog.academic_periods
WHERE id = $1
`

type GetPeriodByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPeriodByID(ctx context.Context, id pgtype.UUID) (GetPeriodByIDRow, error) {
	row := q.db.QueryRow(ctx, getPeriodByID, id)
	var i GetPeriodByIDRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriodBySemester = `-- name: GetPeriodBySemester :one
SELECT id, semester, period_start, period_end, is_active, created_at, updated_at, period_type FROM course_catalog.academic_periods WHERE semester = $1 LIMIT 1
`

func (q *Queries) GetPeriodBySemester(ctx context.Context, semester string) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriodBySemester, semester)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodType,
	)
	return i, err
}

const listAllPeriods = `-- name: ListAllPeriods :many
SELECT id, semester, period_start, period_end, is_active, created_at, updated_at
FROM course_catalog.academic_periods
ORDER BY semester DESC, created_at DESC
`

type ListAllPeriodsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllPeriods(ctx context.Context) ([]ListAllPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listAllPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPeriodsRow{}
	for rows.Next() {
		var i ListAllPeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodsBySemester = `-- name: ListPeriodsBySemester :many
SELECT id, semester, period_start, period_end, is_active, created_at, updated_at
FROM course_catalog.academic_periods
WHERE semester = $1
ORDER BY created_at DESC
`

type ListPeriodsBySemesterRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPeriodsBySemester(ctx context.Context, semester string) ([]ListPeriodsBySemesterRow, error) {
	rows, err := q.db.Query(ctx, listPeriodsBySemester, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeriodsBySemesterRow{}
	for rows.Next() {
		var i ListPeriodsBySemesterRow
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeriod = `-- name: UpdatePeriod :one
UPDATE course_catalog.academic_periods
SET period_end = COALESCE($1, period_end),
    is_active  = COALESCE($2, is_active),
    updated_at = NOW()
WHERE id = $3
RETURNING id, semester, period_start, period_end, is_active, created_at, updated_at
`

type UpdatePeriodParams struct {
	PeriodEnd pgtype.Timestamptz `json:"period_end"`
	IsActive  pgtype.Bool        `json:"is_active"`
	ID        pgtype.UUID        `json:"id"`
}

type UpdatePeriodRow struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (UpdatePeriodRow, error) {
	row := q.db.QueryRow(ctx, updatePeriod, arg.PeriodEnd, arg.IsActive, arg.ID)
	var i UpdatePeriodRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePeriodBySemesterSQL = `-- name: UpdatePeriodBySemesterSQL :one
UPDATE course_catalog.academic_periods
SET period_start = $2, period_end = $3, updated_at = NOW()
WHERE semester = $1
RETURNING id, semester, period_start, period_end, is_active, created_at, updated_at, period_type
`

type UpdatePeriodBySemesterSQLParams struct {
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) UpdatePeriodBySemesterSQL(ctx context.Context, arg UpdatePeriodBySemesterSQLParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, updatePeriodBySemesterSQL, arg.Semester, arg.PeriodStart, arg.PeriodEnd)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodType,
	)
	return i, err
}
