// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: faculties.sql

package db

import (
	"context"
)

const listDepartments = `-- name: ListDepartments :many
SELECT id, faculty_id, slug, code, name, description, sort_order, created_at, updated_at FROM course_catalog.departments
ORDER BY faculty_id, sort_order, name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.FacultyID,
			&i.Slug,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFaculties = `-- name: ListFaculties :many
SELECT id, slug, code, name, sort_order, created_at, updated_at FROM course_catalog.faculties
ORDER BY sort_order, name
`

func (q *Queries) ListFaculties(ctx context.Context) ([]Faculty, error) {
	rows, err := q.db.Query(ctx, listFaculties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Faculty{}
	for rows.Next() {
		var i Faculty
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
