// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatusEnum string

const (
	PaymentOutboxStatusEnumPending   OutboxStatusEnum = "pending"
	PaymentOutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	PaymentOutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"payment_outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type PaymentStatusEnum string

const (
	PaymentPaymentStatusEnumPending   PaymentStatusEnum = "pending"
	PaymentPaymentStatusEnumCompleted PaymentStatusEnum = "completed"
	PaymentPaymentStatusEnumFailed    PaymentStatusEnum = "failed"
	PaymentPaymentStatusEnumExpired   PaymentStatusEnum = "expired"
	PaymentPaymentStatusEnumRefunded  PaymentStatusEnum = "refunded"
)

func (e *PaymentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatusEnum(s)
	case string:
		*e = PaymentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatusEnum: %T", src)
	}
	return nil
}

type NullPaymentStatusEnum struct {
	PaymentStatusEnum PaymentStatusEnum `json:"payment_payment_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatusEnum), nil
}

type OutboxEvent struct {
	ID            pgtype.UUID      `json:"id"`
	EventType     string           `json:"event_type"`
	RoutingKey    string           `json:"routing_key"`
	Payload       []byte           `json:"payload"`
	Status        OutboxStatusEnum `json:"status"`
	RetryCount    int16            `json:"retry_count"`
	MaxRetries    int16            `json:"max_retries"`
	ErrorMessage  pgtype.Text      `json:"error_message"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ProcessedAt   pgtype.Timestamp `json:"processed_at"`
	CorrelationID pgtype.UUID      `json:"correlation_id"`
}

type Payment struct {
	ID             pgtype.UUID        `json:"id"`
	ReferenceID    string             `json:"reference_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	RefundedAmount pgtype.Numeric     `json:"refunded_amount"`
	Currency       string             `json:"currency"`
	Description    string             `json:"description"`
	Status         PaymentStatusEnum  `json:"status"`
	CardBrand      pgtype.Text        `json:"card_brand"`
	CardLast4      pgtype.Text        `json:"card_last4"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
