// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment.payments (reference_id, student_id, amount, currency, description, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (reference_id) DO UPDATE SET reference_id = EXCLUDED.reference_id
RETURNING id, reference_id, student_id, amount, refunded_amount, currency, description, status, card_brand, card_last4, failure_reason, expires_at, completed_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ReferenceID string             `json:"reference_id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// A retried initiate hits the unique reference_id and gets the existing row
// back: the no-op DO UPDATE is what makes RETURNING yield it.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ReferenceID,
		arg.StudentID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.StudentID,
		&i.Amount,
		&i.RefundedAmount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOverduePayments = `-- name: ExpireOverduePayments :execrows
UPDATE payment.payments
SET status = 'expired', updated_at = NOW()
WHERE status = 'pending' AND expires_at <= $1
`

func (q *Queries) ExpireOverduePayments(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireOverduePayments, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaymentByReferenceID = `-- name: GetPaymentByReferenceID :one
SELECT id, reference_id, student_id, amount, refunded_amount, currency, description, status, card_brand, card_last4, failure_reason, expires_at, completed_at, created_at, updated_at FROM payment.payments
WHERE reference_id = $1
`

func (q *Queries) GetPaymentByReferenceID(ctx context.Context, referenceID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReferenceID, referenceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.StudentID,
		&i.Amount,
		&i.RefundedAmount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refundPayment = `-- name: RefundPayment :one
UPDATE payment.payments
SET refunded_amount = refunded_amount + $1::numeric,
    status = CASE
        WHEN refunded_amount + $1::numeric >= amount THEN 'refunded'::payment.payment_status_enum
        ELSE status
    END,
    updated_at = NOW()
WHERE reference_id = $2
  AND status = 'completed'
  AND refunded_amount + $1::numeric <= amount
RETURNING id, reference_id, student_id, amount, refunded_amount, currency, description, status, card_brand, card_last4, failure_reason, expires_at, completed_at, created_at, updated_at
`

type RefundPaymentParams struct {
	Refund      pgtype.Numeric `json:"refund"`
	ReferenceID string         `json:"reference_id"`
}

// The guard sits in the WHERE clause so two concurrent refunds cannot
// together return more than was paid.
func (q *Queries) RefundPayment(ctx context.Context, arg RefundPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, refundPayment, arg.Refund, arg.ReferenceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.StudentID,
		&i.Amount,
		&i.RefundedAmount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.CardBrand,
		&i.CardLast4,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
