// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminStaff = `-- name: CreateAdminStaff :one
INSERT INTO staff.admin_staff (
    email, title, first_name, last_name, faculty, department, phone,
    profile_image_url, position, job_description, responsibilities,
    working_hours, office_location, start_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, email, title, first_name, last_name, faculty, department, phone, profile_image_url, position, job_description, responsibilities, working_hours, office_location, start_date, is_active, created_at, updated_at
`

type CreateAdminStaffParams struct {
	Email            string      `json:"email"`
	Title            string      `json:"title"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Faculty          string      `json:"faculty"`
	Department       string      `json:"department"`
	Phone            string      `json:"phone"`
	ProfileImageUrl  string      `json:"profile_image_url"`
	Position         string      `json:"position"`
	JobDescription   string      `json:"job_description"`
	Responsibilities []byte      `json:"responsibilities"`
	WorkingHours     string      `json:"working_hours"`
	OfficeLocation   string      `json:"office_location"`
	StartDate        pgtype.Date `json:"start_date"`
}

func (q *Queries) CreateAdminStaff(ctx context.Context, arg CreateAdminStaffParams) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, createAdminStaff,
		arg.Email,
		arg.Title,
		arg.FirstName,
		arg.LastName,
		arg.Faculty,
		arg.Department,
		arg.Phone,
		arg.ProfileImageUrl,
		arg.Position,
		arg.JobDescription,
		arg.Responsibilities,
		arg.WorkingHours,
		arg.OfficeLocation,
		arg.StartDate,
	)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Faculty,
		&i.Department,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.Position,
		&i.JobDescription,
		&i.Responsibilities,
		&i.WorkingHours,
		&i.OfficeLocation,
		&i.StartDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminStaffByID = `-- name: GetAdminStaffByID :one
SELECT id, email, title, first_name, last_name, faculty, department, phone, profile_image_url, position, job_description, responsibilities, working_hours, office_location, start_date, is_active, created_at, updated_at FROM staff.admin_staff
WHERE id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetAdminStaffByID(ctx context.Context, id pgtype.UUID) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, getAdminStaffByID, id)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Faculty,
		&i.Department,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.Position,
		&i.JobDescription,
		&i.Responsibilities,
		&i.WorkingHours,
		&i.OfficeLocation,
		&i.StartDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminStaff = `-- name: ListAdminStaff :many
SELECT id, email, title, first_name, last_name, faculty, department, phone, profile_image_url, position, job_description, responsibilities, working_hours, office_location, start_date, is_active, created_at, updated_at FROM staff.admin_staff
WHERE is_active = true
  AND ($1::text IS NULL OR faculty = $1)
ORDER BY last_name, first_name
`

func (q *Queries) ListAdminStaff(ctx context.Context, faculty pgtype.Text) ([]AdminStaff, error) {
	rows, err := q.db.Query(ctx, listAdminStaff, faculty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminStaff{}
	for rows.Next() {
		var i AdminStaff
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Title,
			&i.FirstName,
			&i.LastName,
			&i.Faculty,
			&i.Department,
			&i.Phone,
			&i.ProfileImageUrl,
			&i.Position,
			&i.JobDescription,
			&i.Responsibilities,
			&i.WorkingHours,
			&i.OfficeLocation,
			&i.StartDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminStaff = `-- name: UpdateAdminStaff :one
UPDATE staff.admin_staff
SET email = $2,
    title = $3,
    first_name = $4,
    last_name = $5,
    faculty = $6,
    department = $7,
    phone = $8,
    profile_image_url = $9,
    position = $10,
    job_description = $11,
    responsibilities = $12,
    working_hours = $13,
    office_location = $14,
    start_date = $15,
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, email, title, first_name, last_name, faculty, department, phone, profile_image_url, position, job_description, responsibilities, working_hours, office_location, start_date, is_active, created_at, updated_at
`

type UpdateAdminStaffParams struct {
	ID               pgtype.UUID `json:"id"`
	Email            string      `json:"email"`
	Title            string      `json:"title"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Faculty          string      `json:"faculty"`
	Department       string      `json:"department"`
	Phone            string      `json:"phone"`
	ProfileImageUrl  string      `json:"profile_image_url"`
	Position         string      `json:"position"`
	JobDescription   string      `json:"job_description"`
	Responsibilities []byte      `json:"responsibilities"`
	WorkingHours     string      `json:"working_hours"`
	OfficeLocation   string      `json:"office_location"`
	StartDate        pgtype.Date `json:"start_date"`
}

func (q *Queries) UpdateAdminStaff(ctx context.Context, arg UpdateAdminStaffParams) (AdminStaff, error) {
	row := q.db.QueryRow(ctx, updateAdminStaff,
		arg.ID,
		arg.Email,
		arg.Title,
		arg.FirstName,
		arg.LastName,
		arg.Faculty,
		arg.Department,
		arg.Phone,
		arg.ProfileImageUrl,
		arg.Position,
		arg.JobDescription,
		arg.Responsibilities,
		arg.WorkingHours,
		arg.OfficeLocation,
		arg.StartDate,
	)
	var i AdminStaff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Faculty,
		&i.Department,
		&i.Phone,
		&i.ProfileImageUrl,
		&i.Position,
		&i.JobDescription,
		&i.Responsibilities,
		&i.WorkingHours,
		&i.OfficeLocation,
		&i.StartDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
